import { z } from 'zod'

export const clarificationQuestionSchema = z.object({
  id: z.string(),
  question: z.string(),
  type: z.enum(['text', 'select', 'multiselect', 'boolean', 'number']),
  options: z.array(z.string()).optional(),
  required: z.boolean().default(true),
  placeholder: z.string().optional(),
  validation: z.object({
    min: z.number().optional(),
    max: z.number().optional(),
    pattern: z.string().optional(),
  }).optional(),
})

export const clarificationFormSchema = z.object({
  title: z.string().default('Clarification needed'),
  description: z.string().optional(),
  questions: z.array(clarificationQuestionSchema),
  context: z.string().describe('Additional context about why clarification is needed'),
})

export const planSchema = z.object({
  title: z.string().describe('Title of the learning plan'),
  description: z.string().optional().describe('Brief description of the learning plan'),
  plan: z.array(z.object({
    module: z.object({
      module_name: z.string().describe("the module name"),
      submodule_names: z.array(z.string().describe("name of submodules"))
    })
  })).describe('Array of learning modules with their submodules')
})

export const memoryUpdateSchema = z.object({
  key: z.string().describe('The key to store this information under (e.g., "user.preferences.pace", "user.goals.current")'),
  value: z.string().describe('The information to remember about the user'),
  context: z.string().describe('Brief explanation of why this information is important to remember'),
})

export const createSurfaceSchema = z.object({
  surface_type: z.enum(['sandbox', 'whiteboard', 'quiz', 'gallery', 'timeline', 'explain_block']).describe('The type of learning surface to create'),
  title: z.string().describe('Title for the learning surface'),
  description: z.string().optional().describe('Brief description of what this surface will help the user learn'),
  content: z.string().describe('The main content, code, or instructions for the surface'),
  modality: z.enum(['code', 'exercise', 'quiz', 'image', 'video', 'explain', 'compare', 'timeline', 'whiteboard']).describe('Learning modality this surface supports'),
  context: z.string().describe('Learning context explaining why this surface type was chosen'),
  sandboxTemplate: z.enum(["streamlit-developer", "nextjs-developer" ,"gradio-developer", "vue-developer", "go-developer"]).describe('Name of the template used to generate the fragment.'),
})

export const conductResearchSchema = z.object({
  topic: z.string().describe('Topic to conduct deep research on'),
})

export type ConductResearch = z.infer<typeof conductResearchSchema>

export const fragmentSchema = z.object({
  commentary: z.string().describe(`Describe what you're about to do and the steps you want to take for generating the course plan in great detail.`),
  template: z.enum(["streamlit-developer", "code-interpreter-v1"]).describe('Name of the template used to generate the fragment.'),
  // template_ready: z.boolean().describe('Detect if finished identifying the template.'),
  title: z.string().describe('Short title of the fragment. Max 3 words.'),
  description: z.string().describe('Short description of the fragment. Max 1 sentence.'),
  additional_dependencies: z.array(z.string()).describe('Additional dependencies required by the fragment. Do not include dependencies that are already included in the template.'),
  has_additional_dependencies: z.boolean().describe('Detect if additional dependencies that are not included in the template are required by the fragment.'),
  install_dependencies_command: z.string().describe('Command to install additional dependencies required by the fragment.'),
  // install_dependencies_ready: z.boolean().describe('Detect if finished identifying additional dependencies.'),
  port: z.number().nullable().describe('Port number used by the resulted fragment. Null when no ports are exposed.'),
  file_path: z.string().describe('Relative path to the file, including the file name.'),
  code: z.union([
    z.string().describe('Code generated by the fragment. Only runnable code is allowed.'),
    z.array(z.object({
      file_name: z.string().describe('Name of the file.'),
      file_path: z.string().describe('Relative path to the file, including the file name.'),
      file_content: z.string().describe('Content of the file.'),
    }))
  ]).describe('Code content - either a single string or array of files'),
  needs_clarification: z.boolean().describe('Detect if the fragment needs clarification from the user.'),
  clarification_form: clarificationFormSchema.optional().describe('Dynamic form to collect specific clarifications from the user when needs_clarification is true.'),
  plan: z.array(z.object({
    module: z.object({
      module_name: z.string().describe("the module name"),
      submodule_names:  z.array(z.string().describe("name of submodules "))
    })
  }) )
  // code_finished: z.boolean().describe('Detect if finished generating the code.'),
  // error: z.string().optional().describe('Error message if the fragment is not valid.'),
})

export type ClarificationQuestion = z.infer<typeof clarificationQuestionSchema>
export type ClarificationForm = z.infer<typeof clarificationFormSchema>
export type PlanSchema = z.infer<typeof planSchema>
export type MemoryUpdate = z.infer<typeof memoryUpdateSchema>
export type CreateSurface = z.infer<typeof createSurfaceSchema>
export type FragmentSchema = z.infer<typeof fragmentSchema>
